services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fraud_detection_backend
    ports:
      - "8003:8003"
    volumes:
      - .:/main
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/main
    restart: always